server:
  port: 8080

spring:
  application:
    name: swifttrack-middleware
  datasource:
    url: jdbc:h2:mem:swifttrack;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

swifttrack:
  cms:
    url: http://localhost:8081/ws
  ros:
    url: http://localhost:8082
  wms:
    host: 127.0.0.1
    port: 9090
  saga:
    step-delay-ms: 1200
  outbox:
    poll-interval-ms: 400
